"""Build visual_challenge_labels.csv from images in frames/safe and frames/unsafe."""

from __future__ import annotations

import csv
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
EVAL_DIR = PROJECT_ROOT / "data" / "evaluation"
SAFE_DIR = EVAL_DIR / "frames" / "safe"
UNSAFE_DIR = EVAL_DIR / "frames" / "unsafe"
OUTPUT = EVAL_DIR / "visual_challenge_labels.csv"

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".webp", ".bmp"}


def _collect(folder: Path, true_label: int, category: str) -> list[dict]:
    rows: list[dict] = []
    if not folder.is_dir():
        return rows
    for path in sorted(folder.iterdir()):
        if path.suffix.lower() not in IMAGE_EXTS:
            continue
        rel = path.relative_to(EVAL_DIR).as_posix()
        rows.append(
            {
                "sample_name": path.stem,
                "true_label": true_label,
                "category": category,
                "image_file": rel,
                "notes": f"{'Safe' if true_label == 0 else 'Unsafe'} — {path.name}",
            }
        )
    return rows


def main() -> int:
    SAFE_DIR.mkdir(parents=True, exist_ok=True)
    UNSAFE_DIR.mkdir(parents=True, exist_ok=True)

    rows = _collect(SAFE_DIR, 0, "safe") + _collect(UNSAFE_DIR, 1, "unsafe")

    if not rows:
        print("No images found.")
        print(f"  Put safe images in:   {SAFE_DIR}")
        print(f"  Put unsafe images in: {UNSAFE_DIR}")
        print("See data/evaluation/VISUAL_VALIDATION_GUIDE.md")
        return 1

    fieldnames = ["sample_name", "true_label", "category", "image_file", "notes"]
    with OUTPUT.open("w", newline="", encoding="utf-8") as handle:
        handle.write("# Auto-generated by scripts/build_visual_labels_csv.py\n")
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    safe_n = sum(1 for r in rows if r["true_label"] == 0)
    unsafe_n = sum(1 for r in rows if r["true_label"] == 1)
    print(f"Wrote {len(rows)} rows to {OUTPUT}")
    print(f"  Safe: {safe_n}  |  Unsafe: {unsafe_n}")
    print("\nNext: python scripts/run_model_evaluation.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
